import { useState, useCallback } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useAppContext } from "@/context/AppContext";
import { analyzePlan } from "@/api/plan";
import { useTranslation } from "@/i18n";
import { recoverBrokenChars } from "@/utils/textClean";
import { RefreshCw, Loader, AlertCircle } from "lucide-react";

export function PlanTab() {
  const { state, dispatch: appDispatch } = useAppContext();
  const { t } = useTranslation();
  const data = state.detailPanelData;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // Detect plan completion: all steps have a terminal status
  const allStepsDone = data
    ? data.steps.length > 0 &&
      data.steps.every(
        (s) =>
          s.status === "completed" ||
          s.status === "error" ||
          s.status === "stopped",
      )
    : false;

  const requestAnalysis = useCallback(
    async (force = false) => {
      console.log("[PlanTab] requestAnalysis called", {
        force,
        hasData: !!data,
        hasAnalysis: !!data?.analysis,
        allStepsDone,
      });
      if (!data || (!force && data.analysis)) return;
      if (!allStepsDone && !force) return;

      console.log("[PlanTab] Starting analysis request...");
      setLoading(true);
      setError("");
      try {
        const stepsWithResults = data.steps.map((step, i) => ({
          name: step.name,
          tool: step.tool || "",
          description: step.description || "",
          status: step.status || "pending",
          result: data.results[i] || null,
        }));

        const res = await analyzePlan({
          goal: data.goal,
          steps: stepsWithResults,
          current_step: data.currentStep,
        });

        console.log("[PlanTab] analyzePlan response:", {
          success: res.success,
          analysisLen: res.analysis?.length,
          error: res.error,
        });
        if (res.success && res.analysis) {
          appDispatch({ type: "SET_ANALYSIS", payload: res.analysis });
        } else {
          setError(res.error || "Analysis generation failed");
        }
      } catch (err) {
        setError(String(err));
      } finally {
        setLoading(false);
      }
    },
    [data, allStepsDone, appDispatch],
  );

  // Analysis is now generated by the backend after all steps complete.
  // No auto-trigger needed — the plan_complete SSE event carries the analysis.

  // No plan data yet
  if (!data) {
    return (
      <div className="detail-empty-state">
        <p>{t("empty.plan_hint")}</p>
      </div>
    );
  }

  // Plan in progress — not yet complete
  if (!allStepsDone && !data.analysis) {
    return (
      <div className="detail-empty-state">
        <p>
          {t("status.plan_running") !== "status.plan_running"
            ? t("status.plan_running")
            : "Plan is running. Analysis will appear here when all steps complete."}
        </p>
      </div>
    );
  }

  // Loading analysis
  if (loading) {
    return (
      <div className="detail-empty-state">
        <Loader size={20} className="spin" style={{ marginBottom: 8 }} />
        <p>
          {t("status.analyzing") !== "status.analyzing"
            ? t("status.analyzing")
            : "Generating analysis..."}
        </p>
      </div>
    );
  }

  return (
    <div className="detail-plan-content">
      {/* Error */}
      {error && (
        <div className="detail-error-banner">
          <AlertCircle size={16} className="error-icon" />
          <span className="error-text">{error}</span>
        </div>
      )}

      {/* Analysis markdown — rendered directly in detail-plan-content (matches original) */}
      {data.analysis && (
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {recoverBrokenChars(data.analysis)}
        </ReactMarkdown>
      )}

      {/* No analysis yet but steps are done — use Regenerate to create */}
      {!data.analysis && !error && (
        <div className="detail-empty-state" style={{ flex: 1 }}>
          <p>No analysis available. Click "Regenerate Analysis" to generate.</p>
        </div>
      )}

      {/* Regenerate button — bottom, matches original .detail-regenerate-btn */}
      {allStepsDone && (
        <button
          className="detail-regenerate-btn"
          onClick={() => requestAnalysis(true)}
          disabled={loading}
        >
          <RefreshCw size={14} />
          <span>
            {t("label.regenerate_analysis") !== "label.regenerate_analysis"
              ? t("label.regenerate_analysis")
              : "Regenerate Analysis"}
          </span>
        </button>
      )}

      {/* Regenerate button — bottom, matches original .detail-regenerate-btn */}
      {allStepsDone && (
        <button
          className="detail-regenerate-btn"
          onClick={() => requestAnalysis(true)}
          disabled={loading}
        >
          <RefreshCw size={14} />
          <span>
            {t("label.regenerate_analysis") !== "label.regenerate_analysis"
              ? t("label.regenerate_analysis")
              : "Regenerate Analysis"}
          </span>
        </button>
      )}
    </div>
  );
}
